travis:
  secure:
    BINSTAR_TOKEN: s9XZSdJO7dQRy1vjBRQYvzWktUSjuyRNbkbxvLv8gdrvReA42w76xBCtDAwpjzrk0rmvivWqhRB3j0xeNFgv7+PC+zQsmTmgti6cX6VURosSWyc2tgHMcGg5E9eEz6Owcjql6x9Lap36AXOirJAAr7WO8S6fM/AyIys1Sz8u9yNBu4//hIu3A9V/YL/ZOTKKaws54mEMSuUabp6LHWWCDp90WgIGieOXmUTIPRnbFC3L3E2q5cpg/oQhy6DZTQ/FLV2VHYO4EBP3hp7euc2gSKoxoP4NX8xtqkJFFuW6KJpXHtyoQskHAydDKvT7ftVt1ZrGRQPI1rXLQ7XxvCsGZG43XGuboRA01XhMY7wWsxjYSmlcDPgYwzK8zwW389TNj3AS88Aiq6gOfRoZdC/AeI1kaSYEHA0ePME2y6vIG1/lCRiepaeZMMbgyb74OfXS3J9fVCS2RIptRD2lLiswvJT5/C74fFhqov1hoWlGoyrkl+NikdwgbLL1wsTqDtOqj8doUUw3tawYqlgxd9yunwm0vF2ryZ6bM2t5FvBAX5n/DvDNFp5in5r1z1lLwugdnKpD21JGFvxBs3X+GSaofJmHJHZd5TXUePJycHkCiX/IyCN5pn8noaalsPqwCpGWaILQ4BXeW5H11/1PWx/Rh8+i83jMucG3mjIVFujuwTI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
