travis:
  secure:
    BINSTAR_TOKEN: E+e2zOWoDC70zT5LJH7O1fKiShBuJ5sxSDr2guPVFZDiaBaENOt8zh8/XYd9FH/FltqHlu9mrOL9l+p/Qj4s8qS+qGdBDK0hy6M3ZAj3uvenWyifV9bHXvi7F6A2aOgFZQKQDf7dIs0Ra8UbHR6VYX2/o2+KlgHqFg+RrnXX1b4QjAXECmtD3SjSjvZHl/iJN9S8nDbaUservTZmYOGsaWeDv1Isefc8Q3QASQymt6WZisJ4lC5zv14TgvE07IHi6NBpv9ZS/m6bIadJJT6pzdrSUSAvwqG0cUPpUaoGdIKNGYK5xnNq5Czv/9bp6Y+Fzlz12Uds7o+DB22WGTAHpP8r4M6EuBBLxxZ52SgzxhqzQmQ1ZWl3VFHBtch0zQQ4X7w81o47rEeCurelOCrkr4E7C+qGEAh3Dca+jp62rdfKYMvccdAI8Ow4Hgk5pLaR5jMn+0dtLkFtNzfcHGGm8n7mPtzt5/WL98WZItWRCB2G9Q38cTFQ14hJ3qhJ0jvRtvSp6zMOOAAuEba3qK4tvxsYik1pBUla0w0atkDJ5OsitsO7u8ga79ASdsUNDU2WlCLfyou0VLtwfvAxkHQ6f+binI4lIEijA1H4EAx+LDwXhfJxymXH58Q/xZxdKhLwGD4F0HbhSMyOUwaj+Ry2TxrLz4zZg2lXEi6UMK4rRZY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
